server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://viaduct.proxy.rlwy.net:52584/railway?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: XiILyaUQgkfcZNRlkyCEJDRhGEqqWkZK

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  thymeleaf:
    cache: false
    prefix:
      file: src/main/resources/templates/
  flyway:
    locations: classpath:/dev/db/migration
    baseline-on-migrate: true
    baseline-version: 0
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 107294083364-a41m1iqc4nc7mnj2qb4kuabro68mqi7e.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
            client-name: Google
          facebook:
            client-id: 1192426525219179
            client-secret: 7a85929cafe94b25b28c2952421b7901
            scope: public_profile, email
            client-name: Facebook
jwt:
  secretKey: bd5WNAMWnnQukkW+AqFYD1NV63VfDa73KrV44gsGkvY=
  expiration: 1800
  expiration-refresh-token: 2592000

paypal:
  mode: sandbox
  client:
    id: Ab_XzSvS2Y4Xt_Rh4Ka0fIx0wvg1OdQuyRpnHwlZkziyhALBR7nLulyRlxQ4ylXcDoL00y7v2kdjyn93
    secret: EFcYw7mLeykugw7IH_8C7FAmUiu9m1USPqtzVgmCmcOeATWewwCq1-G3weXfvZvTB6GWoa4BYNf5rOEl

